// Generated by CoffeeScript 1.9.2
var AmznModel, Fetch, Model;

Model = require('ampersand-model');

Fetch = require('ampersand-fetch');

AmznModel = Model.extend({
  sync: function() {
    return Fetch.apply(this, arguments);
  }
});

module.exports = AmznModel;
