// Generated by CoffeeScript 1.9.2
var React, StyleSheet, TabBarIOS, Text, View, styles;

React = require('react-native');

StyleSheet = React.StyleSheet, TabBarIOS = React.TabBarIOS, Text = React.Text, View = React.View;

module.exports = React.createClass({
  getInitialState: function() {
    return {
      selectedTab: 'redTab',
      notifCount: 0,
      presses: 0
    };
  },
  showBlueTab: function() {
    return this.setState({
      selectedTab: 'blueTab'
    });
  },
  showHistory: function() {
    return this.setState({
      selectedTab: 'redTab',
      notifCount: this.state.notifCount + 1
    });
  },
  showGreenTab: function() {
    return this.setState({
      selectedTab: 'greenTab',
      presses: this.state.presses + 1
    });
  },
  _renderContent: function(color, pageText) {
    return React.createElement(View, {
      "style": [
        styles.tabContent, {
          backgroundColor: color
        }
      ]
    }, React.createElement(Text, {
      "style": styles.tabText
    }, pageText), React.createElement(Text, {
      "style": styles.tabText
    }, this.state.presses, " re-renders of the More tab"));
  },
  render: function() {
    return React.createElement(TabBarIOS, null, React.createElement(TabBarIOS.Item, {
      "title": "Blue Tab",
      "selected": this.state.selectedTab === 'blueTab',
      "onPress": this.showBlueTab
    }, this._renderContent('#414A8C', 'Blue Tab')), React.createElement(TabBarIOS.Item, {
      "systemIcon": "history",
      "badge": (this.state.notifCount > 0 ? this.state.notifCount : void 0),
      "selected": this.state.selectedTab === 'redTab',
      "onPress": this.showHistory
    }, this._renderContent('#783E33', 'Red Tab')), React.createElement(TabBarIOS.Item, {
      "systemIcon": "more",
      "selected": this.state.selectedTab === 'greenTab',
      "onPress": this.showGreenTab
    }, this._renderContent('#21551C', 'Green Tab')));
  }
});

styles = StyleSheet.create({
  tabContent: {
    flex: 1,
    alignItems: 'center'
  },
  tabText: {
    color: 'white',
    margin: 50
  }
});
